appdata/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('localization/{locale}', 'LocalizationController@index');


Route::get('/about-model/{id}', 'IndexController@aboutM')->name('aboutM');

Route::get('/user-profile', 'IndexController@userProfile')->name('userProfile');

//Rasel Route
Route::get('/select-plan/{id}', 'IndexController@selectPlan')->name('selectPlan');
Route::post('/select-plan/amount-calculation', 'PaymentController@amountCalculation');
Route::post('/select-plan/amount-with-star', 'PaymentController@starAmount');
Route::post('/select-plan/payment', 'PaymentController@payment');
Route::get('/stripe/success', 'PaymentController@paymentSuccess');
Route::get('/stripe/cancel', 'PaymentController@stripeCancel');
Route::get('/paysera/success', 'PaymentController@paymentSuccess');
Route::get('/paysera/cancel', 'PaymentController@payseraCancel');
Route::get('/paysera/callback', 'PaymentController@payseraCallback');
Route::get('payment-list', 'PaymentListController@index');
Route::get('payment-history', 'PaymentListController@paymentHistory');
Route::get('payment-download', 'PaymentListController@paymentDownload');

Route::get('add-control-payment', 'PaymentController@addControlPayment');
Route::post('add-control-payment/get-price', 'PaymentController@addControlPaymentPrice');

Route::post('add-control-payment/make', 'PaymentController@addControlMakePayment');
Route::get('add-control-payment/success', 'PaymentController@addControllPaymentSuccess');
Route::get('add-control-payment/cancel', 'PaymentController@addControllPaymentCancel');

Route::get('/services', 'SearchServiceController@index')->name('blog');
Route::post('/services/subcategory', 'SearchServiceController@getSubCategory');
Route::get('/services/index-data', 'SearchServiceController@indexData');
Route::get('/services/pagination-data', 'SearchServiceController@paginationData');
Route::post('/vip-profile-amount', 'PaymentController@getProfileAmount')->name('getProfileAmount');
Route::post('/vip-profile-payment', 'PaymentController@profilePayment')->name('profilePayment');

Route::get('profile-payment/success', 'PaymentController@profilePaymentSuccess');
Route::get('profile-payment/cancel', 'PaymentController@profilePaymentCancel');
Route::get('index-vipdata', 'SearchServiceController@indexVipData');
Route::get('public-profile/{id}', 'IndexController@publicProfile');
Route::get('public-profile/{id}/service/{title}/{s_id}', 'IndexController@publicService')->name('publicService');
Route::get('get-user-city', 'SearchServiceController@getUserCity');
Route::get('profile-list', 'SearchServiceController@profileList');
Route::post('get-profile-and-service', 'SearchServiceController@profileAndService');
Route::post('active-service', 'PaymentController@activeService');



//end rasel route


Route::get('test', 'SearchServiceController@test');

Route::namespace('Auth')->group(function () {
	Route::post('registration', 'RegisterController@registration')->name('registration');
});
Route::group(['prefix' => 'user'], function () {

	Route::name('user.')->group(function () {

		Route::post('get-service-gallery-tab', 'IndexController@getServiceGlryTab')->name('getServiceGlryTab');
		Route::namespace('Auth')->group(function () {

			// Route::get('login', 'LoginController@showLoginForm')->name('login');	
			Route::post('login', 'LoginController@login')->name('login.submit');
			Route::post('logout', 'LoginController@logout')->name('logout');
		});
		Route::namespace('User')->group(function () {
			// profile
			Route::post('add-live-zone', 'ProfileController@addLiveZone');
			Route::post('edit-live-zone', 'ProfileController@editLiveZone');
			Route::post('update-live-zone', 'ProfileController@liveZoneUpdate');
			Route::post('delete-live-zone', 'ProfileController@liveZoneDelete');
			Route::post('add-comment', 'CommentController@addComment');
			Route::post('main-comment-replay', 'CommentController@replayMainComment');

			Route::get('profile', 'ProfileController@index')->name('profile');
			Route::get('booking-list', 'ProfileController@bookingList')->name('bookingList');
			Route::get('services/{service}/types/{type}/bookings/{booking}/cancle', 'ProfileController@cancledBooking');
			Route::get('calendar/create', 'CalendarController@index')->name('calendar');
			Route::post('calendar/getsession', 'CalendarController@getSession')->name('getSession');
			Route::post('gallery-file-upload', 'ProfileController@galleryFileUp')->name('galleryFileUp');
			Route::post('gallery-file-remove', 'ProfileController@galleryRemover')->name('galleryRemover');
			Route::post('update-user-picture', 'ProfileController@upPrPic');
			Route::post('process-single-tmp-image', 'ProfileController@setProfilePic');
			Route::post('single-tmp-img-remove', 'ProfileController@removeProfilePic');

			Route::post('cover-image-upload', 'ProfileController@coverImgUpload');
			Route::post('update-cover-img', 'ProfileController@coverImgUpdate');
			Route::post('user-cover-remove', 'ProfileController@userCoverRemover')->name('userCoverRemover');

			Route::post('get-profile-information', 'ProfileController@getProfileInfo');
			Route::post('insert-profile-information', 'ProfileController@insertProfileInfo');
			Route::post('service-address', 'ServicesController@saveServiceAddress')->name('saveServiceAddress');
			Route::get('my-service/{title}/{id}', 'ServicesController@index')->name('myService');
			Route::get('add-my-service', 'ServicesController@add')->name('addMyService');
			Route::post('change-service-details', 'ServicesController@changeServiceDetails')->name('changeServiceDetails');
			Route::post('service-tmp-img', 'ServicesController@serviceTmpImg')->name('serviceTmpImg');
			Route::post('update-service-image', 'ServicesController@updateServiceImg')->name('updateServiceImg');
			Route::post('service-tmp-img-remove', 'ServicesController@serviceTmpImgRemove')->name('serviceTmpImgRemove');
			Route::post('change-service-sub-category', 'ServicesController@changeServiceSubCategory')->name('changeServiceSubCategory');
			Route::post('change-service-inner-category', 'ServicesController@changeServiceInnerCategory')->name('changeServiceInnerCategory');
			Route::post('save-service-category', 'ServicesController@saveServiceCategory')->name('saveServiceCategory');
			Route::post('save-service-gallery-tab', 'ServicesController@saveServiceGlryTab')->name('saveServiceGlryTab');
			Route::post('add-service-gallery-image', 'ServicesController@addServiceGalleryImg')->name('addServiceGalleryImg');
			Route::post('service-gallery-image-upload', 'ServicesController@serviceGalleryImgUpload')->name('serviceGalleryImgUpload');
			Route::post('service-gallery-tmp-image-remove', 'ServicesController@serviceGalleryTmpImgRemove')->name('serviceGalleryTmpImgRemove');

			// calendar
			// Route::get('calendar-list', 'CalendarController@calnedarList')->name('calnedarList');
		});
	});
});
Route::get('/user/calendar/{any}', 'User\CalendarController@index')->where('any', '.*');

appdata/resources/views/inc/footer.blade.php
<section class="footer-section">
	<div class="row mar-0">
		<div class="col-12 col-md-6 col-lg-4">
			<div class="d-con">
				<div class="f-logo"><img src="{{asset('assets/img/logo1.jpg')}}"></div>
				<div class="f-txt">@lang('lang.footer_text')</div>
				<div class="f-card">
					<img src="{{ asset('assets/img/pay-1.png') }}" alt="Left Arrow Key">
					<img src="{{ asset('assets/img/pay-2.png') }}" alt="Left Arrow Key">
					<img src="{{ asset('assets/img/pay-3.png') }}" alt="Left Arrow Key">
					<img src="{{ asset('assets/img/pay-4.png') }}" alt="Left Arrow Key">
					<img src="{{ asset('assets/img/pay-5.png') }}" alt="Left Arrow Key">
				</div>
			</div> 
		</div>
		<div class="col-12 col-md-6 col-lg-5">
			<div class="f-menu">
				<div class="f-menu1">
					<h1>@lang('lang.navigation')</h1>
					<ul>
						<li><a href="#">@lang('lang.home')</a></li>
						<li><a href="#">@lang('lang.pages')</a></li>
						<li><a href="#">@lang('lang.models')</a></li>
						<li><a href="#">@lang('lang.appointment')</a></li>
						<li><a href="#">@lang('lang.faq')</a></li>
						<li><a href="#">@lang('lang.contact')Cont</a></li>
					</ul>
				</div>
				<div class="f-menu1">
					<h1>@lang('lang.navigation')</h1>
					<ul>
						<li><a href="#">@lang('lang.home')</a></li>
						<li><a href="#">@lang('lang.pages')</a></li>
						<li><a href="#">@lang('lang.models')</a></li>
						<li><a href="#">@lang('lang.appointment')</a></li>
						<li><a href="#">@lang('lang.faq')</a></li>
						<li><a href="#">@lang('lang.contact')</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="col-12 col-md-6 col-lg-3">
			<div class="adv">
				<div class="single-content">
					<div class="content-img-p">
						<div class="content-img">
							<img src="{{asset('assets/img/man.jpg')}}">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

appdata/resources/views/inc/header-filter.blade.php
<section class="header-filter">
	<div class="form-section form-sh">
		<div class="form-all">
			<div class="row mar-0">
				<div class="col-12 col-md-6 col-lg-5 pad-0">
					<div class="input-group search-in">
						<input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
						<div class="input-group-append">
							<span class="input-group-text" id="basic-addon2"><i class="fas fa-search"></i></span>
						</div>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-2 pad-0">
					<div class="input-group">
						<div class="ctm-select">
							<div class="ctm-select-txt pad-l-10">
								<span class="select-txt noselect" id="category">@lang('lang.choose')</span>
								<span class="select-arr"><i class="fas fa-caret-down"></i></span>
							</div>
							<div class="ctm-option-box">
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-2 pad-0">
					<div class="form-group">
						<div class="ctm-select">
							<div class="ctm-select-txt pad-l-10">
								<span class="select-txt noselect" id="category">@lang('lang.choose')</span>
								<span class="select-arr"><i class="fas fa-caret-down"></i></span>
							</div>
							<div class="ctm-option-box">
								<div class="ctm-option-ch"><label class="ctm-con mar-0">@lang('lang.men')
										<input type="checkbox" name="category[]" value="men">
										<span class="checkmark"></span>
									</label></div>
								<div class="ctm-option-ch"><label class="ctm-con mar-0">@lang('lang.men')
										<input type="checkbox" name="category[]" value="men">
										<span class="checkmark"></span>
									</label></div>
								<div class="ctm-option-ch"><label class="ctm-con mar-0">@lang('lang.men')
										<input type="checkbox" name="category[]" value="men">
										<span class="checkmark"></span>
									</label></div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-2 pad-0">
					<div class="input-group">
						<div class="ctm-select">
							<div class="ctm-select-txt pad-l-10">
								<span class="select-txt noselect" id="category">@lang('lang.choose')</span>
								<span class="select-arr"><i class="fas fa-caret-down"></i></span>
							</div>
							<div class="ctm-option-box noselect">
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
								<div class="ctm-option noselect">@lang('lang.volksagen')</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-1 pad-0">
					<div class="form-group mar-0">
						<div class="form-check">
							<input class="form-check-input" type="checkbox" id="gridCheck">
							<label class="form-check-label" for="gridCheck">
								@lang('lang.salons')
							</label>
						</div>
						<div class="form-check">
							<input class="form-check-input" type="checkbox" id="gridCheck">
							<label class="form-check-label" for="gridCheck">
								@lang('lang.personal')
							</label>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="form-range">
			<div class="row mar-0">
				<div class="col-12 col-md-6 col-lg-6 r-d">
					<span class="range-tlt">@lang('lang.atstuumas')</span>
					<div class="range-s">
						<input type="range" name="distance" id="html-input-range">
					</div>
					<!-- <div class="demo-output dm">
						<input class="range-slider r1"  type="hidden" value="0,0"/>
					</div> -->
				</div>
				<div class="col-12 col-md-6 col-lg-4 r-d">
					<div class="demo-output dm1">
						<input class="range-slider r2" type="hidden" value="0,50" />
					</div>
				</div>
				<div class="col-12 col-md-6 col-lg-2 r-d">
					<div class="ran-bar">
						<span class="bar-txt">@lang('lang.personal')<i class="fas fa-bars"></i></span> <i class="fa fa-envelope"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="line-h"><span><i class="fas fa-chevron-down"></i></span></div>
</section>

appdata/resources/views/inc/header.blade.php
<div class="header-section header1-section">
	<div class="main-menu">
		<span class="hs-menubar d-block d-lg-none">
			<div class="menu-trigger"> <i class="zmdi zmdi-menu"></i></div>
		</span>
		<nav class="navbar navbar-expand-lg navbar-light">
			<a class="navbar-brand" href="{{url('/')}}"><img src="{{asset('assets/img/logo1.jpg')}}"></a>
			<div class="ss d-none d-md-block">
				<div class="search-show">
					<div class="input-group search-item">
						<input type="text" onclick="searchByTitle(event, this.value)" onkeyup="searchByTitle(event, this.value)" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
						<div class="input-group-append">
							<span class="input-group-text" id="basic-addon2"><i class="fas fa-search"></i></span>
						</div>
					</div>
					<div class="ss-src-result d-none">
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
						<div class="src-rslt-con">sgsgsgs</div>
					</div>
				</div>
			</div>
			<!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class=""><i class="fas fa-bars"></i></span>
			</button> -->
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link active" href="{{url('/')}}">@lang('lang.home')</a>
					</li>
					<li class="nav-item">
						<a class="nav-link dot" href="#">@lang('lang.offers')</a>
					</li>
					<li class="nav-item">
						<a class="nav-link dot" href="{{url('profile-list')}}">@lang('lang.users')</a>
					</li>
					<li class="nav-item">
						<a class="nav-link dot" href="{{url('/user/calendar/create')}}">@lang('lang.sell_services')</a>
						<span class="count-l">2</span>
					</li>
					<li class="nav-item">
						<a class="nav-link dot" href="{{url('/user/booking-list')}}">@lang('lang.buy_services')</a>
						<span class="count-l">2</span>
					</li>
					<li class="nav-item">
						<div class="lan-flag">
							<div class="en-flag {{ (config('app.locale')=='en' ) ? '' : 'd-none' }}">
								<img src="{{ asset('assets/lan/en.png') }}" alt="lan flag" />
							</div>
							<div class="lt-flag {{ (config('app.locale')=='lt' ) ? '' : 'd-none' }}">
								<img src="{{ asset('assets/lan/lt.png') }}" alt="lan flag" />
							</div>
							<div class="rs-flag {{ (config('app.locale')=='rs' ) ? '' : 'd-none' }}">
								<img src="{{ asset('assets/lan/rs.png') }}" alt="lan flag" />
							</div>
							<div class="lan-pop-up d-none">
								<div class="lan-name" onclick="changeLanguage('en')">@lang('lang.english')</div>
								<div class="lan-name" onclick="changeLanguage('lt')">@lang('lang.lithuania')</div>
								<div class="lan-name" onclick="changeLanguage('rs')">@lang('lang.rashiya')</div>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="pro-cnf-area">
				<div class="usr-main-p {{ (Auth::guard('web')->check()) ? '' : 'd-none'}}">
					<a href="{{url('/user/profile')}}"><img class="cover" src="{{asset('assets/img/man.jpg')}}" alt="jglj"></a>
				</div>
				<div class="setting-btn {{ (Auth::guard('web')->check()) ? '' : 'd-none'}}">
					<i class="fas fa-cog"></i>
				</div>
			</div>
			@if(Auth::guard('web')->check())
			<div class="switch-acnt-box">
				<div class="acnt-list">
					<a href="{{url('/user/profile')}}">@lang('lang.profile')</a>
				</div>
				<div class="acnt-list">
					<a href="{{url('/user/calendar/create')}}">@lang('lang.create_calendar')</a>
				</div>
				<div class="acnt-list">
					<a href="{{url('payment-history')}}">@lang('lang.payment_history')</a>
				</div>
				<div class="acnt-list">
					<a href="{{url('/user/booking-list')}}">Booking List</a>
				</div>
				<div class="m-logout">
					<a href="{{ route('user.logout') }}" onclick="event.preventDefault();
					document.getElementById('logout-form').submit();">
						<button class="btn p-btn l-btn">@lang('lang.log_out')</button>
						<form id="logout-form" action="{{ route('user.logout') }}" method="POST" style="display: none;">
							@csrf
						</form>
					</a>
				</div>
			</div>
			@else
			<div class="lg-btn">
				<span><button class="btn p-btn l-btn" data-toggle="modal" data-target="#loginPopUp">@lang('lang.log_in')</button> </span>
				<!-- <span><i class="fas fa-chevron-right"></i> </span> -->
				<!-- <span><button class="btn p-btn r-btn" data-toggle="modal" data-target="#registrationPopUp">@lang('lang.register')</button> </span> -->
			</div>
			@endif
		</nav>
	</div>
	<div class="mb-src-box">
		<div class="ss d-block d-md-none">
			<div class="search-show">
				<div class="input-group search-item">
					<input type="text" onclick="searchByTitle(event, this.value)" onkeyup="searchByTitle(event, this.value)" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
					<div class="input-group-append">
						<span class="input-group-text" id="basic-addon2"><i class="fas fa-search"></i></span>
					</div>
				</div>
				<div class="ss-src-result d-none">
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
					<div class="src-rslt-con">sgsgsgs</div>
				</div>
			</div>
		</div>
	</div>

	<div class="multi-menu d-none d-lg-block">
		<div class="main-menu1">
			<nav class="navbar navbar-expand-lg navbar-light ">
				<button class="navbar-toggler" type="button">
					<span class=""><i class="fas fa-bars"></i></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav mr-auto">
						@php
						$menus = App\Category::get();
						@endphp
						@foreach($menus as $menu)
						<li class="nav-item show-sub-m">
							<a class="nav-link" href="#">{{ $menu->name }}</a>
							<div class="sub-menu sub-menu1">
								@php
								$n = 0;
								$k = $menu->subCategories->count() > 4 ? 4 : $menu->subCategories->count();
								@endphp
								@for($i=0; $i < $k; $i++) <div class="inner-menu">
									@for($j=0; $j < ceil($menu->subCategories->count() / 4); $j++)
										@if($menu->subCategories->count() >= $n + 1) <div class="link-all">
											<div class="inner-tlt"> <a href="">{{ $menu->subCategories[$n]->name }}</a></div>
											<div class="inner-link">
												@php
												$inrCats = $menu->subCategories[$n++]->innerCategories;
												@endphp
												@foreach($inrCats as $inrCat)
												<div><a href="">{{ $inrCat->name }}</a></div>
												@endforeach
											</div>
										</div>
										@endif
										@endfor
							</div>
							@endfor
				</div>
				</li>
				@endforeach
				</ul>
		</div>
		</nav>
	</div>
</div>

<nav class="hs-navigation">
	<ul class="nav-links">
		@php
		$menus = App\Category::get();
		@endphp
		@foreach($menus as $menu)
		<li class="{{ ($menu->subCategories->count()) ? 'has-child' : '' }}">
			<span class="{{ ($menu->subCategories->count()) ? 'its-parent' : '' }}">
				<a href="#">
					<span class="icon">
						<i class="zmdi zmdi-device-hub"></i>
					</span>
					{{ $menu->name }}
				</a>
			</span>
			@if($menu->subCategories->count())
			<ul class="its-children">
				@foreach($menu->subCategories as $subCat)
				<li class="{{ ($subCat->innerCategories->count()) ? 'has-child' : '' }}">
					<span class="{{ ($subCat->innerCategories->count()) ? 'its-parent' : '' }}">
						<a href="#1"> {{ $subCat->name }}</a>
					</span>
					@if($subCat->innerCategories->count())
					<ul class="its-children">
						@foreach($subCat->innerCategories as $innerCat)
						<li> <a href="#1">{{ $innerCat->name }} </a> </li>
						@endforeach
					</ul>
					@endif
				</li>
				@endforeach
			</ul>
			@endif
		</li>
		@endforeach
	</ul>
</nav>
</div>

<div class="search-box header-filter">
	<div class="form-section">
		<div class="form-all">
			<div class="input-group search-in">
				<input type="text" class="form-control" placeholder="Search" aria-label="Recipient's username" aria-describedby="basic-addon2">
				<div class="input-group-append">
					<button class="input-group-text" id="basic-addon2"><i class="fas fa-search"></i></button>
				</div>
			</div>
		</div>
	</div>
	<span class="s-close">&#10006;</span>
</div>

appdata/resources/views/inc/login.blade.php
<!-- Modal -->
<div class="modal fade" id="loginPopUp" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<section class="header-filter mar-0">
					<div class="form-section">
						<div class="form-all">
							<div class="row mar-0">
								<div class="col-12 pad-0">
									<h1 class="title">@lang('lang.login')</h1>
								</div>
								<div class="col-12 pad-0">
									<div class="form-group">
										<a href="{{url('user/redirect',['facebook'])}}">
											<button class="loginBtn loginBtn--facebook" type="button">
												@lang('lang.login_with_facebook')
											</button>
										</a>
										<a href="{{url('user/redirect',['google'])}}">
											<button class="loginBtn loginBtn--google" type="button">
												@lang('lang.login_with_google')
											</button>
										</a>
									</div>
								</div>
								<form action="{{ route('user.login.submit') }}" method="post" class="wth-100-p" onsubmit="validateUserLogin(event);">
									@csrf
									<div class="col-12 pad-0">
										<div class="form-group">
											<label for="LEmail">@lang('lang.email') <span class="c-red">*</span></label>
											<input type="email" id="LEmail" class="form-control" placeholder="Email" aria-label="Email" name="email">
										</div>
									</div>
									<div class="col-12 pad-0">
										<div class="form-group">
											<label for="LPassword">@lang('lang.password')<span class="c-red">*</span></label>
											<input type="password" id="LPassword" class="form-control" placeholder="Password" aria-label="Password" name="password">
										</div>
									</div>
									<div class="col-12 pad-0">
										<h5 class="c-red p-l-10 login-error d-none"></h5>
									</div>
									<div class="col-12 pad-0">
										<div class="form-group">
											<button class="btn btn-ctm">@lang('lang.login')</button>
											<button class="btn r-btn" type="button" data-toggle="modal" data-target="#registrationPopUp" onclick="$('#loginPopUp').modal('hide')">
												@lang('lang.register')
											</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
</div>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v5.0"></script>