appdata/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index')->name('index');
Route::get('localization/{locale}', 'LocalizationController@index');


Route::get('/about-model/{id}', 'IndexController@aboutM')->name('aboutM');

Route::get('/user-profile', 'IndexController@userProfile')->name('userProfile');

//Rasel Route
Route::get('/select-plan/{id}', 'IndexController@selectPlan')->name('selectPlan');
Route::post('/select-plan/amount-calculation', 'PaymentController@amountCalculation');
Route::post('/select-plan/amount-with-star', 'PaymentController@starAmount');
Route::post('/select-plan/payment', 'PaymentController@payment');
Route::get('/stripe/success', 'PaymentController@paymentSuccess');
Route::get('/stripe/cancel', 'PaymentController@stripeCancel');
Route::get('/paysera/success', 'PaymentController@paymentSuccess');
Route::get('/paysera/cancel', 'PaymentController@payseraCancel');
Route::get('/paysera/callback', 'PaymentController@payseraCallback');
Route::get('payment-list', 'PaymentListController@index');
Route::get('payment-history', 'PaymentListController@paymentHistory');
Route::get('payment-download', 'PaymentListController@paymentDownload');

Route::get('add-control-payment', 'PaymentController@addControlPayment');
Route::post('add-control-payment/get-price', 'PaymentController@addControlPaymentPrice');

Route::post('add-control-payment/make', 'PaymentController@addControlMakePayment');
Route::get('add-control-payment/success', 'PaymentController@addControllPaymentSuccess');
Route::get('add-control-payment/cancel', 'PaymentController@addControllPaymentCancel');

Route::get('/services', 'SearchServiceController@index')->name('blog');
Route::post('/services/subcategory', 'SearchServiceController@getSubCategory');
Route::get('/services/index-data', 'SearchServiceController@indexData');
Route::get('/services/pagination-data', 'SearchServiceController@paginationData');
Route::post('/vip-profile-amount', 'PaymentController@getProfileAmount')->name('getProfileAmount');
Route::post('/vip-profile-payment', 'PaymentController@profilePayment')->name('profilePayment');

Route::get('profile-payment/success', 'PaymentController@profilePaymentSuccess');
Route::get('profile-payment/cancel', 'PaymentController@profilePaymentCancel');
Route::get('index-vipdata', 'SearchServiceController@indexVipData');
Route::get('public-profile/{id}', 'IndexController@publicProfile');
Route::get('public-profile/{id}/service/{title}/{s_id}', 'IndexController@publicService')->name('publicService');
Route::get('get-user-city', 'SearchServiceController@getUserCity');
Route::get('profile-list', 'SearchServiceController@profileList');
Route::post('get-profile-and-service', 'SearchServiceController@profileAndService');
Route::post('active-service', 'PaymentController@activeService');



//end rasel route


Route::get('test', 'SearchServiceController@test');

Route::namespace('Auth')->group(function () {
	Route::post('registration', 'RegisterController@registration')->name('registration');
});
Route::group(['prefix' => 'user'], function () {

	Route::name('user.')->group(function () {

		Route::post('get-service-gallery-tab', 'IndexController@getServiceGlryTab')->name('getServiceGlryTab');
		Route::namespace('Auth')->group(function () {

			// Route::get('login', 'LoginController@showLoginForm')->name('login');	
			Route::post('login', 'LoginController@login')->name('login.submit');
			Route::post('logout', 'LoginController@logout')->name('logout');
		});
		Route::namespace('User')->group(function () {
			// profile
			Route::post('add-live-zone', 'ProfileController@addLiveZone');
			Route::post('edit-live-zone', 'ProfileController@editLiveZone');
			Route::post('update-live-zone', 'ProfileController@liveZoneUpdate');
			Route::post('delete-live-zone', 'ProfileController@liveZoneDelete');
			Route::post('add-comment', 'CommentController@addComment');
			Route::post('main-comment-replay', 'CommentController@replayMainComment');

			Route::get('profile', 'ProfileController@index')->name('profile');
			Route::get('booking-list', 'ProfileController@bookingList')->name('bookingList');
			Route::get('services/{service}/types/{type}/bookings/{booking}/cancle', 'ProfileController@cancledBooking');
			Route::get('calendar/create', 'CalendarController@index')->name('calendar');
			Route::post('calendar/getsession', 'CalendarController@getSession')->name('getSession');
			Route::post('gallery-file-upload', 'ProfileController@galleryFileUp')->name('galleryFileUp');
			Route::post('gallery-file-remove', 'ProfileController@galleryRemover')->name('galleryRemover');
			Route::post('update-user-picture', 'ProfileController@upPrPic');
			Route::post('process-single-tmp-image', 'ProfileController@setProfilePic');
			Route::post('single-tmp-img-remove', 'ProfileController@removeProfilePic');

			Route::post('cover-image-upload', 'ProfileController@coverImgUpload');
			Route::post('update-cover-img', 'ProfileController@coverImgUpdate');
			Route::post('user-cover-remove', 'ProfileController@userCoverRemover')->name('userCoverRemover');

			Route::post('get-profile-information', 'ProfileController@getProfileInfo');
			Route::post('insert-profile-information', 'ProfileController@insertProfileInfo');
			Route::post('service-address', 'ServicesController@saveServiceAddress')->name('saveServiceAddress');
			Route::get('my-service/{title}/{id}', 'ServicesController@index')->name('myService');
			Route::get('add-my-service', 'ServicesController@add')->name('addMyService');
			Route::post('change-service-details', 'ServicesController@changeServiceDetails')->name('changeServiceDetails');
			Route::post('service-tmp-img', 'ServicesController@serviceTmpImg')->name('serviceTmpImg');
			Route::post('update-service-image', 'ServicesController@updateServiceImg')->name('updateServiceImg');
			Route::post('service-tmp-img-remove', 'ServicesController@serviceTmpImgRemove')->name('serviceTmpImgRemove');
			Route::post('change-service-sub-category', 'ServicesController@changeServiceSubCategory')->name('changeServiceSubCategory');
			Route::post('change-service-inner-category', 'ServicesController@changeServiceInnerCategory')->name('changeServiceInnerCategory');
			Route::post('save-service-category', 'ServicesController@saveServiceCategory')->name('saveServiceCategory');
			Route::post('save-service-gallery-tab', 'ServicesController@saveServiceGlryTab')->name('saveServiceGlryTab');
			Route::post('add-service-gallery-image', 'ServicesController@addServiceGalleryImg')->name('addServiceGalleryImg');
			Route::post('service-gallery-image-upload', 'ServicesController@serviceGalleryImgUpload')->name('serviceGalleryImgUpload');
			Route::post('service-gallery-tmp-image-remove', 'ServicesController@serviceGalleryTmpImgRemove')->name('serviceGalleryTmpImgRemove');

			// calendar
			// Route::get('calendar-list', 'CalendarController@calnedarList')->name('calnedarList');
		});
	});
});
Route::get('/user/calendar/{any}', 'User\CalendarController@index')->where('any', '.*');

appdata/resources/views/pages/booking-list.blade.php
@extends('layout.app')
@section('style')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/DataTables/css/jquery.dataTables.min.css') }}">
<style type="text/css">
    .gm-style-iw {
        max-width: 300px !important;
        max-height: 300px !important;
    }

    .gm-style-iw-d {
        max-width: 300px !important;
        max-height: 300px !important;
    }
</style>
@endsection
@section('content')
@include('inc.header-filter')
<section class="about-section">
    <div class="link-menu">
        <span class="arrow-l"><i class="fas fa-arrow-left"></i></span>
        <span><a href="#">Booking List</a></span>
    </div>
    <div class="row mar-0">
        <div class="col-12 col-lg-8">
            <div class="booking-list-area">
                <div class="table-responsive">
                    <table id="bookingListTable" class="display" style="width:100%">
                        <thead>
                            <tr>
                                <th>Service</th>
                                <th>Type</th>
                                <th>Worker</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($booking as $book)
                            <tr>
                                <td>{{ $book->service->title }}</td>
                                <td>{{ $book->type->name }}</td>
                                <td>{{ $book->worker->name }}</td>
                                <td>{{ $book->date }}</td>
                                <td>{{ $book->start . ' - ' . $book->end }}</td>
                                <td>
                                    @if( $book->cancle == 1 )
                                    <button class="p-btn btn btn-danger" disabled>Cancle</button>
                                    @elseif( $book->confirm == 1 )
                                    @if( \Carbon\Carbon::now()->diffInMinutes( $book->new_date, false ) <= 0 ) <button class="p-btn btn btn-success" disabled>Complete </button>
                                        @else
                                        <button class="p-btn btn btn-info" disabled>Confirm</button>
                                        @endif
                                        @else
                                        @if( \Carbon\Carbon::now()->diffInMinutes( $book->new_date, false ) <= 0 ) <button class="p-btn btn btn-danger" disabled>Cancle</button>
                                            @else
                                            <button class="p-btn btn btn-danger" data-toggle="modal" data-target="#cancleBooking" onclick="$('.cancle-booking-url').attr('href', '<?= $book->cancle_url; ?>')">Cancle</button>
                                            <button class="p-btn btn btn-warning" disabled>Pending</button>
                                            @endif
                                            @endif
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-4">
            <div class="social-icon">
                <ul>
                    <li class="{{ (Auth::user()->facebook) ? '' : 'd-none' }}"><a class="fb" href="{{ Auth::user()->facebook }}" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="{{ (Auth::user()->twitter) ? '' : 'd-none' }}"><a class="tw" href="{{ Auth::user()->twitter }}" target="_blank"><i class="fab fa-twitter"></i></a></li>
                    <li class="{{ (Auth::user()->gmail) ? '' : 'd-none' }}"><a class="go" href="{{ Auth::user()->gmail }}" target="_blank"><i class="fab fa-goodreads-g"></i></a></li>
                    <li class="{{ (Auth::user()->linkedin) ? '' : 'd-none' }}"><a class="lin" href="{{ Auth::user()->linkedin }}" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                    <li class="{{ (Auth::user()->pinterest) ? '' : 'd-none' }}"><a class="pin" href="{{ Auth::user()->pinterest }}" target="_blank"><i class="fab fa-pinterest-p"></i></a></li>
                </ul>
            </div>
            <div class="pro-box">
                <div class="row">
                    <div class="col-12">
                        <div class="pro-cnt">
                            <div class="pro-name">{{ Auth::user()->name }} {{ Auth::user()->surname }} {{ (Auth::user()->nickname) ? '(' . Auth::user()->nickname . ')' : '' }}</div>
                            <div class="pro-email"><i class="fa fa-envelope"></i> {{ Auth::user()->email }}</div>
                            <div class="pro-phn"><i class="fas fa-mobile-alt"></i>{{ Auth::user()->phone}}</div>
                            <div class="pro-btn">
                                <a href="{{ route('user.profile') }}"><button class="p-btn btn">Profle</button></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="side-blog">
                <section class="blog-section">
                    <div class="pop-master">
                        <h1>Populer Masters</h1>
                    </div>
                    <div class="blog">
                        <div class="blog-img">
                            <img src="{{asset('assets/img/man.jpg')}}">
                        </div>
                        <div class="blog-des">
                            <div class="blog-txt">
                                Lorem Ipsum is simply dummy text of the printing to make
                            </div>
                            <div class="blog-dta star">
                                <span class="date"><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="blog">
                        <div class="blog-img">
                            <img src="{{asset('assets/img/man.jpg')}}">
                        </div>
                        <div class="blog-des">
                            <div class="blog-txt">
                                Lorem Ipsum is simply dummy text of the printing to make
                            </div>
                            <div class="blog-dta star">
                                <span class="date"><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i></span>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

        </div>
    </div>
</section>
<section class="slider-section bg-dark-sec">
    <div id="carouselExampleControls1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{{asset('assets/img/slider1.jpg')}}">
                <div class="carousel-caption">
                    <h1>Third slide label</h1>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{asset('assets/img/slider2.jpg')}}">
                <div class="carousel-caption">
                    <h1>Third slide label</h1>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{{asset('assets/img/slider3.jpg')}}">
                <div class="carousel-caption">
                    <h1>Third slide label</h1>
                    <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<!-- Modal -->
<div class="modal fade" id="cancleBooking" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <section class="header-filter">
                    <div class="form-section">
                        <div class="form-all">
                            <div class="row mar-0">
                                <div class="col-12 pad-0">
                                    <h1 class="title">Are you sure?</h1>
                                </div>
                                <div class="col-12 pad-0">
                                    <div class="form-group btn-area">
                                        <button class="p-btn btn btn-info" type="button" onclick="$('#cancleBooking').modal('hide');">
                                            No
                                        </button>
                                        <a href="" class="cancle-booking-url">
                                            <button class="p-btn btn btn-danger" type="button">
                                                Yes
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script src="{{ asset('assets/DataTables/js/jquery.dataTables.min.js')}}"></script>
<script>
    window.base_url = "<?= url('/') ?>";
</script>
<script>
    $(function() {
        $('#bookingListTable').DataTable();
    });
</script>
@endsection

appdata/resources/views/pages/comment.blade.php
<div class="comment" id="main-cmt-{{$comment['id']}}">
	<div class="row">
		<div class="user-img-c">
			<img src="{{asset('userImage/fixPic/'.$comment['user']['profile_image'])}}" alt="user-img">
		</div>
		<div class="col-12 pad-0">
			<div class="comment-cnt">
				<h2>{{ $comment['user']['surname']}}</h2>
				<h6>
				{{date('d-m-Y',strtotime($comment['created_at']))}} at {{date('H:m a',strtotime($comment['created_at']))}}
				</h6>
				<p>{{ $comment['comment']}}</p>
				<span class="edit-com" onclick="replayModelShow('main-cmt-{{$comment["id"]}}')">@lang('lang.replay')Replay</span>
			</div>
			<div class="cmt-replay">
				
			</div>
		</div>
	</div>
</div>

appdata/resources/views/pages/live-zone-data.blade.php
           <div class="single-content" id="del-live-zone-{{$liveZone->id}}">
              <div class="live-tlt">
                <h1 id="lz-title-{{$liveZone->id}}">{{$liveZone->title}}</h1>
               <div class="edit-info-btn">
                <i title="edit image" class="fa fa-edit" onclick="openLiveZone({{$liveZone->id}})"></i>
                <i title="edit image" class="fa fa-trash" onclick="deleteLiveZone({{$liveZone->id}})"></i>
              </div>
              </div>
              <div class="live-des">
                <p id="lz-des-{{$liveZone->id}}">{{$liveZone->description}}</p>
              </div>
              
              <div class="content-img-p lz-img-{{$liveZone->id}} @if($liveZone->status == 1) imgVideoBlock @else imgVideo @endif">
                <div class="content-img">
                  <img id="lz-img-{{$liveZone->id}}" src="{{asset('liveZone/'.$liveZone->image)}}">
                </div>
              </div>
              
              <div class="content-img-p video lz-video-{{$liveZone->id}}  @if($liveZone->status == 2) imgVideoBlock @else imgVideo @endif">
                  <div class="content-img">
                      <iframe id="lz-video-{{$liveZone->id}}" src="{{$liveZone->image}}">
                      </iframe>
                  </div>
              </div>
             
            </div>

appdata/resources/views/pages/public-profile.blade.php
@extends('layout.app')
@section('style')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/fancybox.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/css/cropper.css') }}">
{{-- <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/app.css') }}"> --}}
<style type="text/css">
  .date a{
    color:#E25B37;
  }
  .url-color{
    color:#E25B37;
  }
</style>
@endsection
@section('content')
@include('inc.header-filter')
<section class="about-section userPro-section">
  <div class="row mar-0">
    <div class="col-12 col-lg-7">
      <div class="userPro-cnt">
        <div class="user-slider" onclick="changeCoverImage(event)">
          <div class="swiper-container ctm-container-4">
            <div class="swiper-wrapper">
              @if($UserCover->count())
              @foreach ($UserCover as $uc)
              <div class="swiper-slide">
                <div class="single-content wh-100">
                  <div class="content-img-p">
                    <div class="content-img">
                      <img src="{{ asset('userImage/coverPic/' . $uc->img) }}" alt="cover-pic">
                    </div>
                  </div>
                </div>
              </div>
              @endforeach
              @else
              <div class="swiper-slide">
                <div class="single-content wh-100">
                  <div class="content-img-p">
                    <div class="content-img">
                      <img src="{{asset('assets/img/default_cover.png')}}" alt="user-img">
                    </div>
                  </div>
                </div>
              </div>
              @endif
            </div>
          </div>
        </div>
        <div class="userPro-bio">
          <div class="row mar-0">
            <div class="userPro-imgM">
              @if($userInfo['profile_image'])
              <img src="{{asset('userImage/fixPic/'. $userInfo['profile_image'])}}" alt="user-img">
              @else
              <img src="{{asset('assets/img/profile_pic.png')}}" alt="user-img">
              @endif
            </div>
            <div class="col-12">
              <div class="userPro-txt">
              <div class="userPro-tlt"><h3 class="setName">{{ $makeName }}</h3>
              </div>
              <div class="userPro-tel">
                <div class="userPro-tel-t">
                  <div class="pro-email"><i class="fa fa-envelope"></i>{{ $userInfo['email'] }}</div>
                  <div class="pro-phn"><i class="fas fa-mobile-alt"></i>{{ $userInfo['phone'] }}</div>
                  <div class="pro-cn"><i class="fas fa-map-marker-alt"></i>{{ $userInfo['address'] }}</div>
                </div>
              </div>
              <div class="social">
                <span>@lang('lang.share')</span>
                <span class="{{ ($userInfo['facebook']) ? '' : 'd-none' }}"><a class="fb" href="{{ ($userInfo['facebook']) ? $userInfo['facebook'] : 'javascript:void(0)' }}" target="_blank"><i class="fab fa-facebook-f"></i></a></span>
                <span class="{{ ($userInfo['twitter']) ? '' : 'd-none' }}"><a class="tw" href="{{ ($userInfo['twitter']) ? $userInfo['twitter'] : 'javascript:void(0)' }}" target="_blank"><i class="fab fa-twitter"></i></a></span>
                <span class="{{ ($userInfo['gmail']) ? '' : 'd-none' }}"><a class="go" href="{{ ($userInfo['gmail']) ? $userInfo['gmail'] : 'javascript:void(0)' }}" target="_blank"><i class="fab fa-goodreads-g"></i></a></span>
                <span class="{{ ($userInfo['linkedin']) ? '' : 'd-none' }}"><a class="lin" href="{{ ($userInfo['linkedin']) ? $userInfo['linkedin'] : 'javascript:void(0)' }}" target="_blank"><i class="fab fa-linkedin-in"></i></a></span>
                <span class="{{ ($userInfo['pinterest']) ? '' : 'd-none' }}"><a class="pin" href="{{ ($userInfo['pinterest']) ? $userInfo['pinterest'] : 'javascript:void(0)' }}" target="_blank"><i class="fab fa-pinterest-p"></i></a></span>

              </div>
            </div>
            <div class="chat-icon"><i class="fas fa-comments"></i></div>
          </div>
        </div>
        <div class="bio-txt">
          <h4 class="bio-txt-tlt">@lang('lang.bio')</h4>
          <p class="bio-txtP">
            {!! $userInfo['bio'] !!}
          </p>
        </div>
      </div>
    </div>
    <div class="live-zona">
      <div class="section-title">@lang('lang.live_zona')</div>
      <div class="live-zona-cnt">
        @if(count($liveZones)>0)
          @foreach ($liveZones as $liveZone)
            <div class="single-content">
              <div class="live-tlt">
                <h1>{{$liveZone->title}}</h1>
              </div>
              <div class="live-des">
                <p>{{$liveZone->description}}</p>
              </div>
              @if($liveZone->status == 1)
              <div class="content-img-p">
                <div class="content-img">
                  <img src="{{asset('liveZone/'.$liveZone->image)}}">
                </div>
              </div>
              @endif
              @if($liveZone->status == 2)
                <div class="content-img-p video">
                  <div class="content-img">
                    <iframe src="{{$liveZone->image}}">
                    </iframe>
                  </div>
                </div>
              @endif
            </div>
          @endforeach
        @endif  
        
      </div>
    </div>
  </div>
  <div class="col-12 col-lg-5">
    <div class="add-pic">
      <div class="row mar-0" id="productGalleryV">
        @foreach($gallery as $gallery)
        <div class="col-6 col-sm-4 col-md-3 pad-0">
          <a href="{{ asset('gallery/'.$gallery->picture) }}" data-fancybox="gallery">
            <div class="single-content">
              <div class="content-img-p">
                <div class="content-img">
                  <img src="{{ asset('gallery/re_'.$gallery->picture) }}" alt="img">
                </div>
              </div>
            </div>
          </a>
        </div>
        @endforeach
      </div>
      <div class="add-p-inp">
        <span class="g-txt">@lang('lang.gallery')</span>
      </div>
    </div>

    <div class="live-zona styling-one">
      <div class="section-title">@lang('lang.my_services')</div>
      @foreach($services as $service)
      <div class="live-zona-cnt">
        <div class="single-content">
          <div class="live-tlt">
            <h1><a href="{{ route('publicService', [$id, $service->title, $service->id]) }}">{{ $service->title }}</a></h1>
          </div>
          <div class="content-img-p">
            <div class="content-img">
              @if($service->img)
              <img src="{{asset('assets/img/services/'. $service->img)}}" class="wth-100-p" alt="service-img">
              @else
              <img src="{{asset('assets/img/services/no_service.png')}}" class="wth-100-p" alt="service-img">
              @endif
            </div>
          </div>
        </div>
      </div>
      @endforeach
      
    </div>
    <div class="side-blog">
      <section class="blog-section">
        <div class="pop-master"><h1>@lang('lang.vip_profile')</h1> </div>
        <div id="vip-profile"></div>
        
      </section>
    </div>

    <div id="vip-services"></div>
          
        

  </div>
</div>
</section>
<section class="slider-section">
  <div id="carouselExampleControls1" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{{asset('assets/img/slider1.jpg')}}">
        <div class="carousel-caption">
          <h1>@lang('lang.third_slider_lavel')</h1>
          <p>@lang('lang.praesent_commodo_cursus_magna_vel scelerisque_nisl_consectetur')</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{asset('assets/img/slider2.jpg')}}">
        <div class="carousel-caption">
          <h1>@lang('lang.third_slider_lavel')</h1>
          <p>@lang('lang.praesent_commodo_cursus_magna_vel scelerisque_nisl_consectetur')</p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{asset('assets/img/slider3.jpg')}}">
        <div class="carousel-caption">
          <h1>@lang('lang.third_slider_lavel')</h1>
          <p>@lang('lang.praesent_commodo_cursus_magna_vel scelerisque_nisl_consectetur')</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls1" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">@lang('lang.previous')</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls1" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">@lang('lang.next')</span>
    </a>
  </div>
</section>



@endsection
@section('script')
<script src="{{ asset('assets/js/jquery.fancybox.js')}}"></script>
<script src="{{ asset('assets/js/cropper.js')}}"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyAnMJd489Qa_hRJXPon9VFHHFpGchq8Ib4"></script> 
<script>
  $(document).ready(function(){
    if ("geolocation" in navigator){
      navigator.geolocation.getCurrentPosition(function(position){
          lat = position.coords.latitude;
          lng = position.coords.longitude;
          getServiceAndProfile(lat, lng);
      },function() {
         
      });
    }
  });

  function getServiceAndProfile(lat, lng){
    var data = new FormData();
    data.append('lat', lat);
    data.append('lng', lng);
    data.append('_token', "{{csrf_token()}}");
    $.ajax( {
        processData: false,
        contentType: false,
        data: data,
        type: 'POST',
        url:'{{url("get-profile-and-service")}}',
        success: function( response ){
            $('#vip-profile').html(response.profiles);
            $('#vip-services').html(response.services);
        }
            
    });
  }
  </script>

<script>
  window.gallery_up =  '<?= route('user.galleryFileUp') ?>';
  window.gallery_remove =  '<?= route('user.galleryRemover') ?>';
  window.cover_pic_remove =  '<?= route('user.userCoverRemover') ?>';
  window.profile_single_tmp_img =  '<?= url("user/process-single-tmp-image") ?>';
  window.profile_single_tmp_remove =  '<?= url("user/single-tmp-img-remove") ?>';
  window.cover_img_upload =  '<?= url("user/cover-image-upload") ?>';
  window.get_profile_info =  '<?= url("user/get-profile-information") ?>';
  window.insert_profile_info =  '<?= url("user/insert-profile-information") ?>';


  $(function() {
    $('[data-fancybox="gallery"]').fancybox({
      thumbs : {
        autoStart : true
      }
    });
  });


</script>

@endsection